name: CI

on:
  push:
    branches:
      - main
  pull_request:

  # EJEMPLOS DE OTROS DISPARADORES (TRIGGERS) COMUNES:

#

# 🏷️ DISPARAR EN TAGS (útil para releases):

# on:

#   push:

#     tags:

#       - 'v*'           # Se ejecuta en tags que empiecen con 'v' (ej: v1.0.0, v2.1.3)

#       - 'release/*'    # Se ejecuta en tags que empiecen con 'release/' (ej: release/1.0)

#       - 'v[0-9]+.[0-9]+.[0-9]+' # Solo tags con formato semántico exacto (v1.2.3)

#

# ⏰ DISPARAR EN HORARIOS (cron jobs):

# on:

#   schedule:

#     - cron: '0 2 * * *'    # Todos los días a las 2:00 AM UTC

#     - cron: '0 9 * * 1'    # Todos los lunes a las 9:00 AM UTC

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci --legacy-peer-deps

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - run: npx nx run-many -t lint test build
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: npx nx fix-ci
        if: always()
